[package]
name = "freya-motion"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { git = "https://github.com/Aiving/freya.git", branch = "feat/transforms" }
freya-core = { git = "https://github.com/Aiving/freya.git", branch = "feat/transforms" }
indexmap = "2.7.1"
skia-safe = "0.81.0"
